# Generated by Django 5.1.6 on 2025-06-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColdData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_phone', models.CharField(help_text='Name and Phone number combined', max_length=150)),
                ('property_listing', models.TextField(blank=True, help_text='Details of property listings', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
