# Generated by Django 5.1.6 on 2025-06-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databank_section', '0002_colddatabank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColdDataBank',
        ),
    ]
